### ISSUE TITLE
Multiple servers

### ISSUE THREAD

**Issue by shapm** [afterlogic/aurora-module-mail-change-password-cpanel-plugin#1]
Hi, in cases where there any many servers and those servers have different users/passwords, what can you do?

**Comment by afterlogic-support** [comment]
In such a case, the best bet is running multiple installations, one for each of the servers.

**Comment by afterlogic-support** [comment]
Also, since the plugin itself is open-source, you're welcome to contribute the modifications which extend its functionality.

**Comment by shapm** [comment]
That's just what I'm doing, I just wanted to know if It was already possible but not documented.
Thanks for the quick reply and for a great webmail client!

**Comment by afterlogic-support** [comment]
Please also note that with the  upcoming version of WebMail we're releasing another plugin which brings password change and user signup:
https://github.com/afterlogic/aurora-module-cpanel-integrator
New WebMail version 8.2.10 should be released in a few days.

**Comment by shapm** [comment]
Thanks for the heads up I hope this new module is made with multiple servers in mind.
